# Generated by Django 4.0.4 on 2022-04-15 18:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CategoriesArticles',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nomCat', models.CharField(max_length=255, unique=True)),
            ],
            options={
                'db_table': 'tb_categories_articles',
            },
        ),
        migrations.CreateModel(
            name='Articles',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nomArticle', models.CharField(max_length=255, unique=True)),
                ('prix', models.IntegerField(default=0)),
                ('categorie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='articles.categoriesarticles')),
            ],
            options={
                'db_table': 'tb_articles',
            },
        ),
    ]
